# Generated by Django 5.2.9 on 2026-01-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_employee_id_remove_material_id_and_more'),
        ('clients', '0002_remove_client_id_client_id_client'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='id',
        ),
        migrations.AddField(
            model_name='expense',
            name='id_expense',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='project',
            name='id_project',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='revenue',
            name='id_revenue',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='project',
            field=models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projecthr',
            name='employee',
            field=models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, to='budget.employee'),
        ),
        migrations.AlterField(
            model_name='projecthr',
            name='project',
            field=models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='hr_resources', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='project',
            field=models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='projects.project'),
        ),
    ]
