# Generated by Django 5.2.9 on 2026-01-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_expense_id_remove_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='montant_en_cours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
