# Generated by Django 5.2.9 on 2026-01-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_revenue_avance_alter_revenue_montant_en_cours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='montant_paye',
        ),
    ]
