# Generated by Django 5.2.9 on 2026-01-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_employee_salaire_employee_cin_and_more'),
        ('projects', '0004_remove_revenue_montant_paye'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assignments', to='budget.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='projects.project')),
            ],
            options={
                'db_table': 'PROJECT_WORKERS',
            },
        ),
    ]
