# Generated by Django 5.2.9 on 2026-01-05 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT_JUSTIFIED', 'Absent justifié'), ('ABSENT_UNJUSTIFIED', 'Absent injustifié')], default='PRESENT', max_length=20)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='projects.projectworker')),
            ],
            options={
                'db_table': 'PROJECT_WORKER_ATTENDANCE',
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
