# Generated by Django 5.2.10 on 2026-01-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectworkerattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='billing_status',
            field=models.CharField(choices=[('NON_FACTURE', 'Non facturé'), ('EN_COURS', 'En cours'), ('FACTURE', 'Facturé')], default='NON_FACTURE', max_length=20, verbose_name='Statut de facturation'),
        ),
    ]
