# Generated by Django 5.2.10 on 2026-01-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_billing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkerattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Présent'), ('HALF_DAY', 'Demi-journée'), ('ABSENT_JUSTIFIED', 'Absent justifié'), ('ABSENT_UNJUSTIFIED', 'Absent injustifié')], default='PRESENT', max_length=20),
        ),
    ]
