# Generated by Django 5.2.11 on 2026-02-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectworkerattendance_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectWorkerAttendance',
        ),
        migrations.DeleteModel(
            name='ProjectWorker',
        ),
    ]
