# Generated by Django 5.2.11 on 2026-02-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_projectworkerattendance_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
