# Generated by Django 5.2.9 on 2026-01-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devis', models.CharField(max_length=50, unique=True)),
                ('objet', models.CharField(max_length=255)),
                ('date_livraison', models.DateField()),
                ('tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='projects.project')),
            ],
            options={
                'db_table': 'QUOTES',
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quote')),
            ],
            options={
                'db_table': 'QUOTE_LINES',
            },
        ),
    ]
