# Generated by Django 5.2.9 on 2026-01-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_remove_quote_id_quote_id_quote_alter_quote_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteline',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
