# Generated by Django 5.2.9 on 2026-01-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quoteline_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='prix_achat_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='quantite_commande',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
