# Generated by Django 5.2.9 on 2026-01-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quoteline_prix_achat_ht_quoteline_quantite_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteline',
            name='prix_achat_ht',
        ),
        migrations.RemoveField(
            model_name='quoteline',
            name='quantite_commande',
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total_ht_fournisseur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='quotes.quote')),
            ],
            options={
                'db_table': 'SUPPLIER_ORDERS',
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_commande', models.IntegerField()),
                ('pu_ht_fournisseur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quote_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quoteline')),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.supplierorder')),
            ],
            options={
                'db_table': 'SUPPLIER_ORDER_LINES',
            },
        ),
    ]
