# Generated by Django 5.2.9 on 2026-01-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_remove_quoteline_prix_achat_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderline',
            name='designation',
            field=models.CharField(default='Autre', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplierorderline',
            name='quote_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quoteline'),
        ),
    ]
