# Generated by Django 5.2.9 on 2026-01-06 19:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_supplierorderline_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierorder',
            old_name='total_ht_fournisseur',
            new_name='total_ht',
        ),
        migrations.RenameField(
            model_name='supplierorderline',
            old_name='pu_ht_fournisseur',
            new_name='montant_ht',
        ),
        migrations.RenameField(
            model_name='supplierorderline',
            old_name='supplier_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='supplierorderline',
            old_name='total_ht',
            new_name='prix_unitaire_fournisseur',
        ),
        migrations.RenameField(
            model_name='supplierorderline',
            old_name='qte_commande',
            new_name='quantite_commandee',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='supplierorderline',
            name='quote_line',
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='id_order',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='nom_commande',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='quotes.quote'),
        ),
        migrations.AlterField(
            model_name='supplierorderline',
            name='designation',
            field=models.CharField(max_length=255),
        ),
    ]
