# Generated by Django 5.2.9 on 2026-01-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_rename_total_ht_fournisseur_supplierorder_total_ht_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorderline',
            name='order',
        ),
        migrations.CreateModel(
            name='QuoteTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(db_column='id_quote', on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='quotes.quote')),
            ],
            options={
                'db_table': 'QUOTE_TRACKING',
            },
        ),
        migrations.CreateModel(
            name='QuoteTrackingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tracking', models.ForeignKey(db_column='id_tracking', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quotetracking')),
            ],
            options={
                'db_table': 'QUOTE_TRACKING_LINES',
            },
        ),
        migrations.DeleteModel(
            name='SupplierOrder',
        ),
        migrations.DeleteModel(
            name='SupplierOrderLine',
        ),
    ]
