# Generated by Django 5.2.10 on 2026-01-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_remove_supplierorderline_order_quotetracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotetracking',
            name='bc_number',
            field=models.CharField(blank=True, help_text='Numéro du Bon de Commande', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotetracking',
            name='bl_number',
            field=models.CharField(blank=True, help_text='Numéro du Bon de Livraison', max_length=50, null=True),
        ),
    ]
