# Generated by Django 5.2.10 on 2026-01-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quotetracking_bc_number_quotetracking_bl_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotetracking',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Numéro de Facture', max_length=50, null=True),
        ),
    ]
