# Generated by Django 5.2.11 on 2026-02-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_quotetracking_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='quotes.quote')),
            ],
            options={
                'db_table': 'QUOTE_GROUPS',
            },
        ),
        migrations.AddField(
            model_name='quoteline',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='quotes.quotegroup'),
        ),
    ]
