# Generated by Django 5.2.11 on 2026-02-06 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_quotegroup_quoteline_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotegroup',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='quotegroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Groupe optionnel pour organiser les lignes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='quotes.quotegroup'),
        ),
    ]
