# Generated by Django 5.2.11 on 2026-02-06 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_alter_quotegroup_options_quotegroup_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteTrackingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='quotes.quotetracking')),
            ],
            options={
                'db_table': 'QUOTE_TRACKING_GROUPS',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quotetrackingline',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Groupe optionnel pour organiser les lignes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='quotes.quotetrackinggroup'),
        ),
    ]
