# Generated by Django 5.2.11 on 2026-02-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_quotetrackinggroup_quotetrackingline_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='change_status',
            field=models.CharField(choices=[('unchanged', 'Inchangé'), ('modified', 'Modifié'), ('new', 'Nouveau')], default='unchanged', help_text='Statut de modification pour suivi visuel', max_length=20),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='original_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='original_prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='original_quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotetrackingline',
            name='change_status',
            field=models.CharField(choices=[('unchanged', 'Inchangé'), ('modified', 'Modifié'), ('new', 'Nouveau')], default='unchanged', help_text='Statut de modification pour suivi visuel', max_length=20),
        ),
        migrations.AddField(
            model_name='quotetrackingline',
            name='original_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotetrackingline',
            name='original_prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotetrackingline',
            name='original_quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
