# Generated by Django 5.2.11 on 2026-02-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_quoteline_remise_quotetrackingline_remise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteline',
            name='remise',
        ),
        migrations.RemoveField(
            model_name='quotetrackingline',
            name='remise',
        ),
    ]
