# Generated by Django 5.2.11 on 2026-02-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_remove_quoteline_remise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remise en pourcentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='quotetrackingline',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remise en pourcentage', max_digits=5),
        ),
    ]
