# Generated by Django 5.2.11 on 2026-02-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0017_quoteline_remise_quotetrackingline_remise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteline',
            name='remise',
        ),
        migrations.RemoveField(
            model_name='quotetrackingline',
            name='remise',
        ),
        migrations.AddField(
            model_name='quote',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remise globale en pourcentage', max_digits=5),
        ),
    ]
