# Generated by Django 5.2.9 on 2026-01-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='id_client',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
