# Generated by Django 5.2.10 on 2026-01-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_adresse_client_statut_client_type_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ice',
            field=models.CharField(blank=True, help_text="Identifiant Commun de l'Entreprise (15 chiffres)", max_length=20, null=True),
        ),
    ]
