# Generated by Django 5.2.9 on 2026-01-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('projects', '0002_remove_expense_id_remove_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='id_invoice',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.project'),
        ),
    ]
