# Generated by Django 5.2.9 on 2026-01-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fonction', models.CharField(max_length=100)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'EMPLOYEES',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('unite', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'MATERIALS',
            },
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_usine', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=12)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manutention_ouvriers', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_ouvrier', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_perte', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vrc_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='budget.material')),
            ],
            options={
                'db_table': 'MATERIAL_COSTS',
            },
        ),
    ]
