# Generated by Django 5.2.9 on 2026-01-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='id_employee',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='material',
            name='id_material',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materialcost',
            name='material',
            field=models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='budget.material'),
        ),
    ]
