# Generated by Django 5.2.9 on 2026-01-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_employee_id_remove_material_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salaire',
        ),
        migrations.AddField(
            model_name='employee',
            name='cin',
            field=models.CharField(default='000000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='prenom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='salaire_semaine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
