# Generated by Django 5.2.10 on 2026-01-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_employee_salaire_employee_cin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExpense',
            fields=[
                ('id_expense', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('date', models.DateField(verbose_name='Date')),
                ('category', models.CharField(choices=[('TRANSPORT', 'Transport'), ('FUEL', 'Carburant / Auto'), ('LOGISTICS', 'Logistique'), ('OFFICE', 'Bureau & Administratif'), ('OTHER', 'Autre')], default='OTHER', max_length=50, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'GENERAL_EXPENSES',
                'ordering': ['-date'],
            },
        ),
    ]
