# Generated by Django 5.2.11 on 2026-02-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_monthlylabourcost_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlylabourcost',
            name='unique_year_month',
        ),
    ]
