# Generated by Django 5.2.9 on 2026-01-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=255)),
                ('nbr_salaries', models.IntegerField(default=1)),
                ('taux_affectation', models.FloatField(default=100.0)),
                ('duree_travail_mois', models.FloatField(default=1.0)),
                ('jours_par_mois', models.IntegerField(default=26)),
                ('salaire_journalier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'HR_ESTIMATION_ROWS',
            },
        ),
    ]
