# Generated by Django 5.2.10 on 2026-01-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type_supplier', models.CharField(choices=[('GRAND', 'Grand Fournisseur'), ('PETIT', 'Petit Fournisseur')], default='PETIT', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('ice', models.CharField(blank=True, help_text="Identifiant Commun de l'Entreprise", max_length=20, null=True)),
                ('rc', models.CharField(blank=True, help_text='Registre de Commerce', max_length=50, null=True)),
                ('patente', models.CharField(blank=True, max_length=50, null=True)),
                ('cnss', models.CharField(blank=True, max_length=50, null=True)),
                ('if_fiscal', models.CharField(blank=True, help_text='Identifiant Fiscal', max_length=50, null=True)),
                ('category', models.CharField(blank=True, help_text='Secteur ou catégorie de produits', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'SUPPLIERS',
                'ordering': ['name'],
            },
        ),
    ]
