# Generated by Django 5.2.10 on 2026-01-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id_invoice', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(help_text="Date d'achat")),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant TTC', max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Numéro de facture ou référence', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PAYE', 'Payée'), ('IMPAYE', 'Impayée')], default='PAYE', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description des produits/services', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'SUPPLIER_INVOICES',
                'ordering': ['-date'],
            },
        ),
    ]
